name: Dummy Workflow

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the code
        uses: actions/checkout@v4 # Fetches the latest code from GitHub 

      - name: Setup Node js 
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Transpile the code
        run: npm run build

      - name: Cache the built files
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}
        
  test:
    runs-on: ubuntu-latest
    needs: build # Runs only after 'build' succeeds
    steps:
      - name: Grab the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test

      - name: Cache the coverage reports
        uses: actions/cache@v4
        with:
          path: coverage
          key: ${{ runner.os }}-coverag